// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplicationManager.Data.Models;

public partial class Company
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Postcode { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();

    public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();
}