// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplicationManager.Data.Models;

public partial class JobApplication
{
    public int Id { get; set; }

    public string Jobtitle { get; set; }

    public string Url { get; set; }

    public int? CompanyId { get; set; }

    public virtual Company Company { get; set; }
}