// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplicationManager.Data.Models;

public partial class User
{
    public string Firstname { get; set; }

    public string Surname { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string Postcode { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Homepage { get; set; }

    public string BitlyApiKey { get; set; }

    public string SmtpServer { get; set; }

    public string SmtpUser { get; set; }

    public string SmtpPass { get; set; }

    public int SmtpPort { get; set; }

    public string SmtpServerOption { get; set; }

    public string LatexPath { get; set; }

    public string ApplicationPath { get; set; }
}