// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplicationManager.Domain.Entities;

public partial class Company
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Postcode { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string UserGuid { get; set; }

    public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();

    public virtual User User { get; set; }
}