// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplicationManager.Domain.Entities;

public partial class JobApplication
{
    public int Id { get; set; }

    public string Jobtitle { get; set; }

    public string Url { get; set; }

    public int? CompanyId { get; set; }

    public string UserGuid { get; set; }

    public DateTime EmailSent { get; set; }

    public string InterviewQuestions { get; set; }

    public DateTime? FirstInterview { get; set; }

    public DateTime? SecondInterview { get; set; }

    public DateTime? ThirdInterview { get; set; }

    public string InterviewNotes { get; set; }

    public string Status { get; set; }

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }
}