//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.2.6.3
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApplicattionManager.Entrities
{
   public partial class CompanyEntity
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public CompanyEntity()
      {
         ContactPersonEntity = new System.Collections.Generic.HashSet<global::JobApplicattionManager.Entrities.ContactPersonEntity>();
         JobApplicationEntity = new System.Collections.Generic.HashSet<global::JobApplicattionManager.Entrities.JobApplicationEntity>();

         Init();
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      public string City { get; set; }

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      public string Name { get; set; }

      public string Postcode { get; set; }

      public string Street { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual ICollection<global::JobApplicattionManager.Entrities.ContactPersonEntity> ContactPersonEntity { get; private set; }

      public virtual ICollection<global::JobApplicattionManager.Entrities.JobApplicationEntity> JobApplicationEntity { get; private set; }

   }
}

