//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplicationManager.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobApplicationManager.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application as ähnelt.
        /// </summary>
        internal static string ApplicationSubjectprefix {
            get {
                return ResourceManager.GetString("ApplicationSubjectprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ms ähnelt.
        /// </summary>
        internal static string ContactAddressFemale {
            get {
                return ResourceManager.GetString("ContactAddressFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mr ähnelt.
        /// </summary>
        internal static string ContactAddressMale {
            get {
                return ResourceManager.GetString("ContactAddressMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        /// </summary>
        internal static string ContactGenderMale {
            get {
                return ResourceManager.GetString("ContactGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string ContactGenderUnknown {
            get {
                return ResourceManager.GetString("ContactGenderUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HR Departnemt ähnelt.
        /// </summary>
        internal static string ContactHRDepartment {
            get {
                return ResourceManager.GetString("ContactHRDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dear Ms ähnelt.
        /// </summary>
        internal static string ContactSalutationFemale {
            get {
                return ResourceManager.GetString("ContactSalutationFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dear Mister ähnelt.
        /// </summary>
        internal static string ContactSalutationMale {
            get {
                return ResourceManager.GetString("ContactSalutationMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dear sir and dear madam ähnelt.
        /// </summary>
        internal static string ContactSalutationUnknown {
            get {
                return ResourceManager.GetString("ContactSalutationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email sent ähnelt.
        /// </summary>
        internal static string CsvEmailSent {
            get {
                return ResourceManager.GetString("CsvEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;{0}&lt;br&gt;
        ///&lt;p&gt;You will find the documents for my application attached.&lt;br&gt;
        ///&lt;p&gt;Sincerley&lt;/p&gt;
        ///&lt;p align=left&gt;{1}&lt;br&gt;
        ///&lt;center&gt;&lt;img src=&quot;&quot;cid:{2}&quot;&quot; width=&quot;&quot;10%&quot;&quot;&gt;&lt;/center&gt;&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string EmailHTML {
            get {
                return ResourceManager.GetString("EmailHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}
        ///
        ///You will find the documents for my application attached.
        ///
        ///Sincerely
        ///{1} ähnelt.
        /// </summary>
        internal static string EmailPlain {
            get {
                return ResourceManager.GetString("EmailPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hello ähnelt.
        /// </summary>
        internal static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email Settings ähnelt.
        /// </summary>
        internal static string SettingsEmailHeader {
            get {
                return ResourceManager.GetString("SettingsEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email options: ähnelt.
        /// </summary>
        internal static string SettingsEmailOptions {
            get {
                return ResourceManager.GetString("SettingsEmailOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a Email Option ähnelt.
        /// </summary>
        internal static string SettingsEmailOptionsPicker {
            get {
                return ResourceManager.GetString("SettingsEmailOptionsPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP Password ähnelt.
        /// </summary>
        internal static string SettingsEmailPass {
            get {
                return ResourceManager.GetString("SettingsEmailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your SMTP Password ähnelt.
        /// </summary>
        internal static string SettingsEmailPassHelper {
            get {
                return ResourceManager.GetString("SettingsEmailPassHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP Port ähnelt.
        /// </summary>
        internal static string SettingsEmailSmtpPort {
            get {
                return ResourceManager.GetString("SettingsEmailSmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your SMTP Server&apos;s Port ähnelt.
        /// </summary>
        internal static string SettingsEmailSmtpPortHelper {
            get {
                return ResourceManager.GetString("SettingsEmailSmtpPortHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP Server URL ähnelt.
        /// </summary>
        internal static string SettingsEmailSmtpServer {
            get {
                return ResourceManager.GetString("SettingsEmailSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your SMTP Server ähnelt.
        /// </summary>
        internal static string SettingsEmailSmtpServerHelper {
            get {
                return ResourceManager.GetString("SettingsEmailSmtpServerHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP Username ähnelt.
        /// </summary>
        internal static string SettingsEmailUser {
            get {
                return ResourceManager.GetString("SettingsEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your SMTP Username ähnelt.
        /// </summary>
        internal static string SettingsEmailUserHelper {
            get {
                return ResourceManager.GetString("SettingsEmailUserHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit.ly Token ähnelt.
        /// </summary>
        internal static string SettingsExternalBitLyToken {
            get {
                return ResourceManager.GetString("SettingsExternalBitLyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your Bit.Ly Token [Optional] ähnelt.
        /// </summary>
        internal static string SettingsExternalBitLyTokenHelper {
            get {
                return ResourceManager.GetString("SettingsExternalBitLyTokenHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External Services ähnelt.
        /// </summary>
        internal static string SettingsExternalHeader {
            get {
                return ResourceManager.GetString("SettingsExternalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to your LaTEX installation ähnelt.
        /// </summary>
        internal static string SettingsExternalLatexPath {
            get {
                return ResourceManager.GetString("SettingsExternalLatexPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Path ähnelt.
        /// </summary>
        internal static string SettingsExternalLatexPathButton {
            get {
                return ResourceManager.GetString("SettingsExternalLatexPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please place there your LaTEX Installation Path ähnelt.
        /// </summary>
        internal static string SettingsExternalLatexPathHelper {
            get {
                return ResourceManager.GetString("SettingsExternalLatexPathHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JobApplicationManager - Settings ähnelt.
        /// </summary>
        internal static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City ähnelt.
        /// </summary>
        internal static string SettingsUserCity {
            get {
                return ResourceManager.GetString("SettingsUserCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your city ähnelt.
        /// </summary>
        internal static string SettingsUserCityHelper {
            get {
                return ResourceManager.GetString("SettingsUserCityHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emailaddress ähnelt.
        /// </summary>
        internal static string SettingsUserEmail {
            get {
                return ResourceManager.GetString("SettingsUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your email address ähnelt.
        /// </summary>
        internal static string SettingsUserEmailHelper {
            get {
                return ResourceManager.GetString("SettingsUserEmailHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firstname ähnelt.
        /// </summary>
        internal static string SettingsUserFirstname {
            get {
                return ResourceManager.GetString("SettingsUserFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your firstname ähnelt.
        /// </summary>
        internal static string SettingsUserFirstnameHelper {
            get {
                return ResourceManager.GetString("SettingsUserFirstnameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User details ähnelt.
        /// </summary>
        internal static string SettingsUserHeader {
            get {
                return ResourceManager.GetString("SettingsUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Homepage ähnelt.
        /// </summary>
        internal static string SettingsUserHomepage {
            get {
                return ResourceManager.GetString("SettingsUserHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your homepage address [Optional] ähnelt.
        /// </summary>
        internal static string SettingsUserHomepageHelper {
            get {
                return ResourceManager.GetString("SettingsUserHomepageHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phonenumber ähnelt.
        /// </summary>
        internal static string SettingsUserPhone {
            get {
                return ResourceManager.GetString("SettingsUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your phone number ähnelt.
        /// </summary>
        internal static string SettingsUserPhoneHelper {
            get {
                return ResourceManager.GetString("SettingsUserPhoneHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street ähnelt.
        /// </summary>
        internal static string SettingsUserStreet {
            get {
                return ResourceManager.GetString("SettingsUserStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your street ähnelt.
        /// </summary>
        internal static string SettingsUserStreetHelper {
            get {
                return ResourceManager.GetString("SettingsUserStreetHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surname ähnelt.
        /// </summary>
        internal static string SettingsUserSurname {
            get {
                return ResourceManager.GetString("SettingsUserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your surname ähnelt.
        /// </summary>
        internal static string SettingsUserSurnameHelper {
            get {
                return ResourceManager.GetString("SettingsUserSurnameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zip/Postcode ähnelt.
        /// </summary>
        internal static string SettingsUserZip {
            get {
                return ResourceManager.GetString("SettingsUserZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your ZIP-Code ähnelt.
        /// </summary>
        internal static string SettingsUserZipHelper {
            get {
                return ResourceManager.GetString("SettingsUserZipHelper", resourceCulture);
            }
        }
    }
}
